from __future__ import annotations

PLUGIN_ID = "core.visualisation"
STATE_SERVICE_KEY = f"{PLUGIN_ID}.state"

PLOT_MIN_HEIGHT = 170

# Fixed settings height. Do not couple this to the outer panel height.
# The settings content itself should scroll if it overflows.
SETTINGS_HEIGHT = 156

DEFAULT_DATASHADE_THRESHOLD = 50_000
DEFAULT_INTERACTIVE_SAMPLE_LIMIT = 50_000
DEFAULT_MAX_SELECTION_IDS = 100_000

INTERNAL_X = "__x__"
INTERNAL_Y = "__y__"
INTERNAL_ROW_ID = "__row_id__"
INTERNAL_LABEL_RAW = "__label_raw__"
INTERNAL_LABEL_DISPLAY = "__label_display__"
INTERNAL_LABEL_COLOUR = "__label_colour__"

SELECTION_SOURCE_LOOKUP_LIMIT = 5000
SELECTION_SOURCE_LOOKUP_CHUNK_SIZE = 500
SELECTION_SOURCE_LOOKUP_FALLBACK_LIMIT = 250
SELECTION_OVERLAY_DEBUG_LIMIT = 8

COVERAGE_SAMPLE_MIN_ROWS = 25_000
COVERAGE_SAMPLE_X_BINS = 192
COVERAGE_SAMPLE_Y_BINS = 192
COVERAGE_SAMPLE_FRACTION = 0.75
COVERAGE_SAMPLE_MAX_DIRECT_ROWS = 1_000_000
COVERAGE_SAMPLE_CANDIDATE_POOL = 750_000


INTERACTIVE_DENSITY_UNDERLAY_ENABLED = True
INTERACTIVE_DENSITY_UNDERLAY_MIN_ROWS = 250_000
INTERACTIVE_DENSITY_UNDERLAY_ALPHA = 0.25
INTERACTIVE_DENSITY_CANVAS_WIDTH = 450
INTERACTIVE_DENSITY_CANVAS_HEIGHT = 320

INTERACTIVE_DENSITY_GREY_RGB = (0.18, 0.18, 0.18)
INTERACTIVE_DENSITY_ALPHA_GAMMA = 0.65

FULL_RANGE_REL_TOL = 1.0e-3

STALE_ATTACH_REFRESH_SKIP_AFTER_SECONDS = 2.0